version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  labels:
    - "dependencies"
    # Add default Kodiak `merge.automerge_label`
    - "automerge"    
  open-pull-requests-limit: 10
  reviewers:
  - aav7fl
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  labels:
    - "dependencies"
    # Add default Kodiak `merge.automerge_label`
    - "automerge"
  open-pull-requests-limit: 10
  reviewers:
  - aav7fl
