language: node_js
branches:
  only:
  - master
dist: xenial
os: linux
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - vendor/bundle
    - /home/travis/.rvm/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  # https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem update --system
  - gem install bundler

install:
  - bundle install 
  - npm install

script:
  - bundle exec rake test

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  # Remove skip_cleanup with Deployment v2
  skip_cleanup: true 
  on:
    branch: master

notifications:
  email:
    recipients:
      - $NOTIFICATION_EMAIL
    on_success: never
    on_failure: always
