language: node_js
sudo: false
branches:
  except:
  - gh-pages
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - vendor/bundle
    - /home/travis/.rvm/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem install bundler

install:
  - bundle install --deployment
  - npm install

script:
  - bundle exec rake test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  on:
    branch: master

notifications:
  email:
    recipients:
      - $NOTIFICATION_EMAIL
    on_success: never
    on_failure: always
