language: node_js
sudo: false
branches:
  except:
  - gh-pages
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - vendor/bundle

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_USERNAME: aav7fl
  - GH_REPO: website
  - GH_SOURCE_BRANCH: master
  - GH_DEST_BRANCH: gh-pages
  - secure: "o7dbtMMpx5wNp70QxyC4G52losqbuHue5ch4573JavwkhrPkEbV/ZA6iKfHVyxxH8SapWQjmHFaR9G00yBDeMOI6NqLHGcE3A2PyNHcT7lfz1jxGCU8TxFIJxMgrVYIRcvQTNurKREnykD2LGXvkR3WqN0V3mMWPEpl9xZ47aTjVu8rq3hUlLMm8GPC/Fy72AW2ouuLIsD1Ks2o36zknuaewT7nBM2X9RUV2rpLtj57x0SEfZq0GyKEEjDCYfQYJXXQjoiZDR0k2qbJKYOxu1MoUUGraWGTVtQHxUa7TnCkBYkbL3wlotfJMdRI0Yg3ma9t/NanTUPnZyFoJi1vs6nGrxvVosD5XyFcEPW6wi+G9pkh/0/9P5PyoI2VkPVyRQcoYa7anYEjSuZPU/Z6BCPdAfY9kL6kZ7BeH9ThEaAeUBeUx2WixSZf3U4phpjIVWpDPxMyv0jlS+gvy8cATGhrK8BgywRw0fr5PRN2jN/AoIyBiFg35uF+824hyW1ZUZFLTw6e8LKTfcsvf5njNSMO6b12vrpAHort1Nz8opTP0liONWGBrhO8s6fCxP8rfaknTyGvDTLb1ft+mfUwaOu8jgcBTqSjXUnXZMnkSC3hXobSs4B+yzbHZxt6ghlrfwLqYynxBgu6TgLkUaN7P2mqDCsifQ01nQGq1blgl7YY="

before_install:
  # Workaround for npm which rvm issue https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-245937070
  - if [ -f node_modules/.bin/which ]; then mv node_modules/.bin/which node_modules/.bin/which.backup; fi
  - rvm install 2.5.1 && rvm use 2.5.1
  - if [ -f node_modules/.bin/which.backup ]; then mv node_modules/.bin/which.backup node_modules/.bin/which; fi
  - gem install bundler
  - gem install bundler

install:
  - bundle install --deployment
  - npm install

script:
  - bundle exec rake test

deploy:
  provider: script
  script: "./_scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - secure: "VqHik+zJ1vPFS9cwHWg/FRYrPOLiQn92okqaREsnKhulnx+nRErOdMnDtnCaOuKPNk0oM6O4mlW02ciACjmHYtx7kSvQT2kSc1vUFC6kMzq4NJ4yBzvonWNnTQRp45GRvCOZ9sy1RpW/aEnlmjObFDVR3YP/RQ1BqR32YpCRqmnCaGLfTDkaLnMueHLN0jrgEityhghAGXxAAfNehJq6OBMRYVTc9Z4DImqmUv20ZWiSjib7lnCv7ax30lGHnE8VBsggZRMyAd54GJRQp9nHF8tiN4LZ61yAWrYrYneU+f8vQeSLUamQdjg6Dw9zRC5eWHZBYs6TWj0I2AnnjkNLfMVKX16JG//z4gZw3YQoGoF4uniRTMdJc7UJAzKt6ZmisYWCujk57wR9Lc7KDRn6mhgWl/TsSqntkRH3L0gtozLo7umbOrE02eepu2QjZrJRqmJzcMVG+far+oPzvhCMcQkqotd8UO4a7tDagSFrvav1SJGZh415vBIudelWwKfMa7WS0QwsCL1tDkq8FU4+FxOLMHdYM2/sZNdGNyjtAGAxZEPquQMecHfJrBXAOQN7i/LskBq4rdFRM9B5pOjs3s/t1dTxqQFtsGLhtHz1zwFJpbK1fj9aaAVXG8vFMX4CYIU5trXb21cziAzNssTRPrPYcy51A9joWOTn77SOo2k="
    on_success: never
    on_failure: always
