version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
    - "aav7fl"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"    

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
    - "aav7fl"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"    
